dist: xenial
sudo: false
language: python

python:
  - "3.5"
  - "3.7"

addons:
  apt:
    packages:
      - libwebkitgtk-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk-3-dev
      - libgtk3.0
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - freeglut3-dev
      - libnotify-dev

install:
  - pip3 install --upgrade pip
  - pip3 install pathlib2 pytest docutils pygments
  - pip3 install wxpython
  - python setup.py install
script:
  pytest