dist: trusty
sudo: false
language: cpp
python:
- "3.5"
install:
- echo "extra installation not needed"
script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_FLAGS_RELEASE="-O0 -Wall -Wno-deprecated-declarations -static-libgcc" -DCMAKE_BUILD_TYPE=Debug ..
  - time make build -j $NPROC
#- python setup.py build --nowx
