dist: xenial
sudo: false
language: python

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - libwebkitgtk-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk-3-dev
      - libgtk3.0
      - autoconf
      - build-essential
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - libpng16-16
      - libpng-dev
      - freeglut3-dev
      - libnotify-dev

install:
  - pip3 install --upgrade pip
  - pip3 install pathlib2 pytest docutils pygments
  - pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
  - python setup.py install
script:
  pytest