dist: xenial
sudo: false
language: python

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - libwebkitgtk-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk-3-dev
      - libgtk3.0
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - freeglut3-dev
      - libnotify-dev

install:
  - pip3 install --upgrade pip
  - pip3 install pathlib2 pytest docutils pygments
  - echo "Python version var"
  - echo $TRAVIS_PYTHON_VERSION
  - wget "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.4-cp$TRAVIS_PYTHON_VERSION-cp$TRAVIS_PYTHON_VERSIONm-linux_x86_64.whl"
  - pip install wxPython-4.0.4-cp$TRAVIS_PYTHON_VERSION-cp$TRAVIS_PYTHON_VERSIONm-linux_x86_64.whl
script:
  pytest