dist: xenial
sudo: false
language: python

python:
  - "3.5"
  - "3.7"

addons:
  apt:
    packages:
      - libwebkitgtk-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk2.0-dev
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - freeglut3-dev
      - libnotify-dev
before_install:
  - sudo apt-get update
install:
  - pip3 install --upgrade pip
  - pip3 install wxpython pytest docutils pygments
  - python setup.py install
script:
  pytest